<?xml version="1.0" ?>
<robot name="nss_ur5" xmlns:xacro="http://ros.org/wiki/xacro" xmlns:tesseract="https://github.com/tesseract-robotics/tesseract" tesseract:make_convex="true">
  <!--xacro args for UR Macro-->
  <xacro:arg name="ur_type" default="ur5"/>
  <xacro:arg name="joint_limit_params" default="$(find ur_description)/config/$(arg ur_type)/joint_limits.yaml"/>
  <xacro:arg name="kinematics_params" default="$(find ur_description)/config/$(arg ur_type)/default_kinematics.yaml"/>
  <xacro:arg name="physical_params" default="$(find ur_description)/config/$(arg ur_type)/physical_parameters.yaml"/>
  <xacro:arg name="visual_params" default="$(find ur_description)/config/$(arg ur_type)/visual_parameters.yaml"/>
		
	<xacro:arg name="transmission_hw_interface" default=""/>
	<xacro:arg name="safety_limits" default="false"/>
	<xacro:arg name="safety_pos_margin" default="0.15"/>
	<xacro:arg name="safety_k_position" default="20"/>
	
	<xacro:arg name="use_fake_hardware" default="true" />
	<xacro:arg name="fake_sensor_commands" default="false" />
	<xacro:arg name="robot_ip" default="192.168.2.100"/>
  <xacro:arg name="computer_ip" default="0.0.0.0"/>
  <xacro:arg name="script_filename" default="$(find ur_client_library)/resources/external_control.urscript"/>
  <xacro:arg name="output_recipe_filename" default="$(find ur_robot_driver)/resources/rtde_output_recipe.txt"/>
  <xacro:arg name="input_recipe_filename" default="$(find ur_robot_driver)/resources/rtde_input_recipe.txt"/>

  <!-- Add World -->
  <material name="light_gray">
    <color rgba="0.7 0.7 0.7 1"/>
  </material>

  <material name="dark_gray">
    <color rgba="0.3 0.3 0.3 1"/>
  </material>
  
  <link name="world"/>

  <!-- Add Floor -->
  <xacro:property name="length" value="9.0"/>
  <xacro:property name="width" value="6.0"/>
  <link name="floor">
    <visual>
      <origin xyz="0 -${width/10} 0.001" rpy="0 0 0"/>
      <geometry>
        <box size="${length} ${width} 0.001"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 -${width/10} 0.001" rpy="0 0 0"/>
      <geometry>
        <box size="${length} ${width} 0.001"/>
      </geometry>
    </collision>
  </link>
  <joint name="world_to_floor" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <parent link="world"/>
    <child link="floor"/>
  </joint>

  <!-- Add table -->
  <link name="table">
    <visual>
      <geometry>
        <mesh filename="package://snp_automate_2023/meshes/visual/steel_table.ply"/>
      </geometry>
      <material name="dark_gray"/>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package://snp_automate_2023/meshes/collision/steel_table.ply"/>
      </geometry>
    </collision>
    <collision>
      <origin xyz="0 0 0.726" rpy="0 0 0"/>
      <geometry>
        <box size="1.9 0.95 0.05"/>
      </geometry>
    </collision>
  </link>

  <joint name="floor_to_table" type="fixed">
    <parent link="floor"/>
    <child link="table"/>
  </joint>

  <!-- ur arm instantiation -->
  <xacro:include filename="$(find ur_description)/urdf/ur_macro.xacro"/>
  <xacro:arg name="ur_type" default="$(arg ur_type)"/>
  <xacro:arg name="use_fake_hardware" default="$(arg use_fake_hardware)"/>
  <xacro:arg name="fake_sensor_commands" default="$(fake_sensor_commands)"/>
  <xacro:ur_robot
      name="ur5"
      tf_prefix=""
      parent="table"
      joint_limits_parameters_file="$(arg joint_limit_params)"
      kinematics_parameters_file="$(arg kinematics_params)"
      physical_parameters_file="$(arg physical_params)"
      visual_parameters_file="$(arg visual_params)"
      transmission_hw_interface="$(arg transmission_hw_interface)"
      safety_limits="$(arg safety_limits)"
      safety_pos_margin="$(arg safety_pos_margin)"
      safety_k_position="$(arg safety_k_position)"
      use_fake_hardware="$(arg use_fake_hardware)"
      fake_sensor_commands="$(arg fake_sensor_commands)"
      initial_positions="${xacro.load_yaml('$(find snp_automate_2023)/config/initial_positions.yaml')}"
      robot_ip="$(arg robot_ip)"
      reverse_ip="$(arg computer_ip)"
      script_filename="$(arg script_filename)"
      output_recipe_filename="$(arg output_recipe_filename)"
      input_recipe_filename="$(arg input_recipe_filename)">
    <origin xyz="-0.61 0 0.723" rpy="0 0 0"/>
  </xacro:ur_robot>

  <!-- <joint name="table_to_base" type="fixed">
    <parent link="table"/>
    <child link="base_link"/>
    <origin xyz="-0.61 0 0.723" rpy="0 0 0"/>
  </joint> -->

  <!-- Add End Effector Components -->
  <xacro:property name="radius" value="${3.75 * 0.0254 / 2.0}"/>
  <xacro:property name="length" value="${5.875 * 0.0254}"/>
  <xacro:property name="small_radius" value="${1.0 * 0.0254 / 2.0}"/>
  <xacro:property name="small_length" value="${2.0 * 0.0254}"/>
  <link name="ee">
    <visual>
      <geometry>
        <mesh filename="package://snp_automate_2023/meshes/collision/ati_spindle.ply"/>
      </geometry>
    </visual>
    <visual>
      <geometry>
        <mesh filename="package://snp_automate_2023/meshes/collision/ati_hose.ply"/>
      </geometry>
    </visual>
    <visual>
      <geometry>
        <mesh filename="package://snp_automate_2023/meshes/collision/ati_tool.ply"/>
      </geometry>
    </visual>
    <visual>
      <geometry>
        <mesh filename="package://snp_automate_2023/meshes/collision/ati_bracket.ply"/>
      </geometry>
    </visual>
    <visual>
      <geometry>
        <mesh filename="package://snp_automate_2023/meshes/collision/ati_standoff.ply"/>
      </geometry>
    </visual>
    <visual>
      <geometry>
        <mesh filename="package://snp_automate_2023/meshes/collision/hc10_standoff.ply"/>
      </geometry>
    </visual>
    <visual>
      <geometry>
        <mesh filename="package://snp_automate_2023/meshes/collision/sensor_bracket.ply"/>
      </geometry>
    </visual>
    <!-- Collision -->
    <collision>
      <geometry>
        <mesh filename="package://snp_automate_2023/meshes/collision/ati_spindle.ply"/>
      </geometry>
    </collision>
    <collision>
      <geometry>
        <mesh filename="package://snp_automate_2023/meshes/collision/ati_hose.ply"/>
      </geometry>
    </collision>
    <collision>
      <geometry>
        <mesh filename="package://snp_automate_2023/meshes/collision/ati_tool.ply"/>
      </geometry>
    </collision>
    <collision>
      <geometry>
        <mesh filename="package://snp_automate_2023/meshes/collision/ati_bracket.ply"/>
      </geometry>
    </collision>
    <collision>
      <geometry>
        <mesh filename="package://snp_automate_2023/meshes/collision/ati_standoff.ply"/>
      </geometry>
    </collision>
    <collision>
      <geometry>
        <mesh filename="package://snp_automate_2023/meshes/collision/hc10_standoff.ply"/>
      </geometry>
    </collision>
    <collision>
      <geometry>
        <mesh filename="package://snp_automate_2023/meshes/collision/sensor_bracket.ply"/>
      </geometry>
    </collision>
  </link>

  <joint name="tool0_to_ee" type="fixed">
    <parent link="tool0"/>
    <child link="ee"/>
    <origin rpy="0.0 0.0 ${radians(45)}"/>
  </joint>

  <xacro:arg name="ros_distro" default="humble"/>
  <xacro:if value="${'$(arg ros_distro)' > 'foxy'}">
    <xacro:property name="camera_cal" value="${xacro.load_yaml('$(find snp_automate_2023)/config/calibration.yaml')}" />
  </xacro:if>
  <xacro:unless value="${'$(arg ros_distro)' > 'foxy'}">
    <xacro:property name="camera_cal" value="${load_yaml('$(find snp_automate_2023)/config/calibration.yaml')}" />
  </xacro:unless>

  <link name="camera_frame"/>
  <joint name="tool0_to_camera" type="fixed">
    <parent link="flange"/>
    <child link="camera_frame"/>
    <origin xyz="${camera_cal['camera_mount_to_camera_pos']['x']} ${camera_cal['camera_mount_to_camera_pos']['y']} ${camera_cal['camera_mount_to_camera_pos']['z']}"
            rpy="${camera_cal['camera_mount_to_camera_rpy']['x']} ${camera_cal['camera_mount_to_camera_rpy']['y']} ${camera_cal['camera_mount_to_camera_rpy']['z']}" />
  </joint>

  <!-- Add TCP -->
  <link name="sand_tcp">
    <visual>
      <geometry>
        <mesh filename="package://snp_automate_2023/meshes/collision/sponge.ply"/>
      </geometry>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package://snp_automate_2023/meshes/collision/sponge.ply"/>
      </geometry>
    </collision>
  </link>

  <joint name="sand_tcp_joint" type="fixed">
    <parent link="tool0"/>
<!--    <origin xyz="-0.158 -0.158 0.123" rpy="0.0 ${radians(90)} ${radians(-135)}"/>-->
    <origin xyz="-0.149 ${-0.149 - 0.005} 0.083" rpy="0.0 ${radians(-90)} ${radians(-135)}"/>
<!--    <parent link="ee"/>-->
<!--    <origin xyz="${-0.186 - 0.038} 0.0 ${0.08325}" rpy="0.0 ${radians(90)} 0.0"/>-->
    <child link="sand_tcp"/>
  </joint>
</robot>
